version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - PORT=8080
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRY=24h
    networks:
      - leaderboard-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - leaderboard-network

networks:
  leaderboard-network:
    driver: bridge

volumes:
  redis-data: 